language: python
python:
  - "2.6"
  - "2.7"
install:
    - pip install numpy
    - pip install matplotlib
    - pip install svn+http://svn.scipy.org/svn/scipy/trunk/#egg=scipy
script: python dexiTest.py
