language: python

python:
  - "2.6"
  - "2.7"

install:
    - pip install numpy
    - pip install matplotlib
    - pip install scipy

script: python dexiTest.py

before_install:
    - sudo apt-get install libblas-dev
    - sudo apt-get install liblapack-dev
    - sudo apt-get install gfortran
